version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_package:
- ps: "$version =\n[System.Reflection.Assembly]::LoadFile(\"$env:APPVEYOR_BUILD_FOLDER\\Unickq.SpecFlow.Selenium.Plugin\\bin\\Release\\Unickq.SpecFlow.Selenium.SpecFlowPlugin.dll\").GetName().Version\n$versionStr = \"{0}.{1}.0-alfa{2}\" -f ($version.Major, $version.Minor, $version.Build)\n\n$content = (Get-Content $env:APPVEYOR_BUILD_FOLDER\\nuget.nuspec) \n$content = $content -replace '\\$version\\$',$versionStr\n\n$content | Out-File $env:APPVEYOR_BUILD_FOLDER\\nuget.compiled.nuspec"
test:
  assemblies:
    only:
    - Unickq.SpecFlow.Selenium.Example.dll
after_test:
- cmd: NuGet pack nuget.compiled.nuspec
artifacts:
- path: '**\Unickq.SpecFlow.Selenium*.nupkg'