version: 1.1.1.{build}

environment:
  packageVersion: 1.1.1
  
init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: if(!$env:appveyor_repo_tag_name){ $env:nugetVersion = $env:packageVersion+ "-beta-" + $env:appveyor_build_number } else { $env:nugetVersion = $env:appveyor_repo_tag_name}
- ps: Update-AppveyorBuild -Version $env:buildVersion
    
image: Visual Studio 2017
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\Unickq.SpecFlow.Selenium.SpecFlowPlugin.csproj'
  version: '{version}'
  package_version: $(nugetVersion)
  assembly_version: $(buildVersion)
  file_version: $(buildVersion)
  informational_version: $(nugetVersion)
  
before_build:
- nuget restore

build:
  verbosity: minimal

test:
  assemblies:
    only:
    - Unickq.SpecFlow.Selenium.Example.dll   

artifacts:
- path: '**\Unickq.SpecFlow.Selenium*.nupkg'